config/routes.rb
Rails.application.routes.draw do
  #this will take us to the homepage on opening the application
  root :to => 'animals#index'

  resources :animals do
    resources :sightings, :except => [:show, :index]
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  validates :kind, :presence => true

  def self.sighted
    where(sighted: true)
  end

  def self.not_sighted
    where(sighted: false)
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  validates :date, :presence => true

  scope :recent_sightings, -> {where("date >=?", Time.now.beginning_of_day)}
  def self.current_sightings
    where(date: Time.now.beginning_of_day)
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    @seen_animals = Animal.sighted
    @unseen_animals = Animal.not_sighted
    @recent_sightings = Sighting.recent_sightings

    @current_sightings = Sighting.current_sightings
  end

  def show
    @animal = Animal.find(params[:id])
    @sightings = @animal.sightings.sort_by {|obj| obj.date}
    render :display
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      flash[:notice] = "Your animal was added to the list"
      redirect_to animals_path
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    # render :edit
    # if render :edit matches def edit, render :edit can be removed
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
      redirect_to animals_path
    else
      render :edit
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  private
    def animal_params
      params.require(:animal).permit(:kind, :sighted)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController

  def new
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new
  end

  def create
    @animal = Animal.find(params[:animal_id])
    @sighting = @animal.sightings.new(sighting_params)
    @animal.update(sighted: true)
    if @sighting.save
      redirect_to animal_path(@sighting.animal)
    else
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:animal_id])
    @sighting = Sighting.find(params[:id])
    @params = params
    @x = @sighting.lat_lng.x
    @y = @sighting.lat_lng.y
  end

  def update
    @sighting = Sighting.find(params[:id])
    if @sighting.update!(sighting_params)
      redirect_to animal_path(@sighting.animal)
    else
      render :edit
    end
  end

  def destroy
    @sighting = Sighting.find(params[:id])
    @sighting.destroy
    redirect_to animal_path(@sighting.animal)
  end

private
  def sighting_params
    params.require(:sighting).permit(:date, :lat_lng)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal do |f| %>
  <!-- <%= f.label :TYPE %> -->
  <%= f.text_field :kind %>
  <%= f.submit  %>
<% end %>

<%= render "layouts/errors", :object => @animal %>

app/views/animals/display.html.erb
<div class="panel" style="text-align:center;margin:10px;border:1px solid black;width:800px;margin:0 auto;">
  <div class="panel-header">
    <h2><%= @animal.kind %></h2>
  </div>
  <div class="panel-body">
    <a href="http://thecatapi.com"><img src="http://thecatapi.com/api/images/get?format=src&type=gif" style="width: 600px; height: 400px; margin: 0, auto;" alt=""></a>
  </div>

  <% if @animal.sightings.any? %>
  <h4>Here are the sightings for this animal:</h4>

    <% @sightings.each do |sighting| %>
        <h3>Last Date Seen: <%= sighting.date %></h3>
        <p>Last Location Seen: <%= sighting.lat_lng.x %>,<%= sighting.lat_lng.y %></p>
        <%= link_to "Edit", edit_animal_sighting_path(@animal, sighting) %>
        <%= link_to "NEW", new_animal_sighting_path(@animal) %>
        <%= link_to "Delete", animal_sighting_path(@animal, sighting), :data => {:confirm => "Are you sure?", :method => "delete"} %>
    <% end %>
  <% else %>
    <p>There are no sightings yet!</p>
  <% end %>
  <hr>

  <p><%= link_to "HOME", animals_path %></p>
  <p><%= link_to "ADD SIGHTING", new_animal_sighting_path(@animal) %></p>
  <p><%= link_to "EDIT", edit_animal_path %></p>
  <p><%= link_to "DELETE", animal_path, :data => {
      :confirm => "You sure?", :method => "delete"
    } %></p>
</div>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render "form" %> 

app/views/animals/index.html.erb
<% content_for(:title, "Animals | Master List") %>

<div class="panel" style="text-align:center;margin:10px;border:1px solid black;width:800px;margin:0 auto;">
  <h1>Animals</h1>
  <%= link_to "ADD ANIMAL", new_animal_path %>
</div>
<br>
<div class="panel" style="text-align:center;margin:10px;border:1px solid black;width:800px;margin:0 auto;">
  <div class="row">
    <div class="col-md-6">
      <ol style="list-style:numbered;">
        <% @seen_animals.each do |animal| %>
          <li><%= link_to animal.kind, animal_path(animal) %></li>
        <% end %>
      </ol>
    </div>
    <div class="col-md-6">
      <ol>
        <% @unseen_animals.each do |animal| %>
          <li><%= link_to animal.kind, animal_path(animal) %></li>
        <% end %>
      </ol>
    </div>
  </div>
</div><br>
<div class="panel" style="text-align:center;margin:10px;border:1px solid black;width:800px;margin:0 auto;">
  <h1>Recent Sightings</h1>
  <% @recent_sightings.each do |sighting| %>
    <li><%= sighting.date %></li>
  <% end %>
</div>
<br>
<div class="panel" style="text-align:center;margin:10px;border:1px solid black;width:800px;margin:0 auto;">
  <h1>Current Sightings</h1>
  <% @current_sightings.each do |sighting| %>
    <li><%= sighting.date %></li>
  <% end %>
</div>




<!-- <%= image_tag "trees.jpeg" %> -->

app/views/animals/new.html.erb
<div class="card" style="text-align:center;margin:10px;border:1px solid black;width:800px;margin:0 auto;">
  <div class="card-header">
    <h2>Hey there, Friend. What's your favorite animal?</h2>
  </div>

  <%= render "form" %>

  <p><%= link_to "HOME", animals_path %></p>
</div>

app/views/layouts/_errors.html.erb
<div class="card">
  <% if object.errors.any? %>
    <h1>ERRORS:</h1>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
    
  </body>
</html>

app/views/sightings/_form.html.erb
<%= render('layouts/errors', :object => @sighting) %>

<%= form_for [@animal, @sighting] do |f| %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <% if @params %>
    <%= f.label :lat_lng, 'NEW latitude, longitude:' %>
    <%= f.text_field :lat_lng, :value => "#{@x}, #{@y}" %>
  <% else %>
    <%= f.label :lat_lng, 'Enter the latitude, longitude:' %>
    <%= f.text_field :lat_lng, :value => "ex: 100.44, 55.23" %>
  <% end %>
    <p><%= f.submit %></p>

<% end %>

app/views/sightings/edit.html.erb
<h1>Edit your sighting</h1>

<%= render "form" %> 

app/views/sightings/new.html.erb
<h1>New sighting for <%= @animal.kind %>? Enter it below:</h1>

<%= render 'form' %>